[package]
name = "kiwmi"
version = "0.1.0"
authors = ["buffet <dev@buffet.sh>"]
edition = "2018"

[dependencies]
env_logger = "0.6.0"
log = "0.4.0"

[dependencies.wlroots]
version = "0.2.4"
features = ["static", "unstable"]
